import { type Experience } from "@prisma/client";

export const data: Partial<Experience>[] = [
  {
    name: "Wilderness Adventure",
    cost: 150,
    description:
      "Explore the rugged wilderness with a seasoned guide. Experience the thrill of hunting, hiking, and canoeing in one of the most beautiful locations in the country.",
    location: "Yellowstone National Park, Wyoming",
    latitude: 44.42677,
    longitude: -110.58845,
    tags: ["hunting", "hiking", "canoeing"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Camping in the Mountains",
    cost: 100,
    description:
      "Escape the hustle and bustle of the city and spend a weekend camping in the mountains. Enjoy the fresh air, beautiful scenery, and the opportunity to fish and hike to your heart's content.",
    location: "Sierra Nevada Mountains, California",
    latitude: 37.865101,
    longitude: -119.538329,
    tags: ["camping", "fishing", "hiking"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Rock Climbing Excursion",
    cost: 200,
    description:
      "Join an experienced rock climbing guide for a day of adventure and excitement. Learn the basics of rock climbing and experience the thrill of scaling a mountain.",
    location: "Smith Rock State Park, Oregon",
    latitude: 44.277599,
    longitude: -121.139079,
    tags: ["rock climbing", "lessons"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Kayak and Canoe Adventure",
    cost: 75,
    description:
      "Explore the peaceful waters of a local lake or river with a guided kayak or canoe excursion. Enjoy the tranquility and natural beauty of the surrounding area while learning the basics of paddling.",
    location: "Lake Tahoe, California",
    latitude: 38.894857,
    longitude: -119.934508,
    tags: ["kayaking", "canoeing", "lessons"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Sailing and Swimming Excursion",
    cost: 250,
    description:
      "Join a sailing expert for a day of adventure and fun on the water. Learn the basics of sailing and enjoy the opportunity to swim and snorkel in the beautiful waters of a local bay.",
    location: "Biscayne Bay, Florida",
    latitude: 25.73139,
    longitude: -80.250719,
    tags: ["sailing", "swimming", "lessons"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Ski and Snowboard Adventure",
    cost: 350,
    description:
      "Join a group of experienced skiers and snowboarders for a day of adventure on the slopes. Experience the thrill of skiing and snowboarding in one of the most beautiful locations in the country.",
    location: "Aspen, Colorado",
    latitude: 39.191098,
    longitude: -106.817538,
    tags: ["skiing", "snowboarding"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Horseback Riding Excursion",
    cost: 200,
    description:
      "Join an experienced guide for a guided horseback riding excursion through the beautiful countryside. Enjoy the tranquility of the surroundings and the opportunity to learn the basics of horseback riding.",
    location: "Smoky Mountains, Tennessee",
    latitude: 35.611111,
    longitude: -83.4658,
    tags: ["riding", "lessons"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Fishing Expedition",
    cost: 500,
    description:
      "Join a professional fisherman for a day of fishing on a local lake or river. Learn the basics of fishing and experience the thrill of catching a big one.",
    location: "Lake Michigan, Illinois",
    latitude: 41.878114,
    longitude: -87.629798,
    tags: ["fishing", "lessons"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Hiking and Camping Adventure",
    cost: 200,
    description:
      "Join a group of experienced hikers for a weekend of adventure and camping in the wilderness. Enjoy the natural beauty of the surrounding area and the opportunity to camp under the stars.",
    location: "Grand Canyon National Park, Arizona",
    latitude: 36.10698,
    longitude: -112.112997,
    tags: ["hiking", "camping"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Kayaking and Fishing Excursion",
    cost: 250,
    description:
      "Join a guided kayak excursion through the beautiful waters of a local bay or river. Experience the thrill of kayaking and enjoy the opportunity to swim and snorkel in the clear waters.",
    location: "Chesapeake Bay, Maryland",
    latitude: 38.907192,
    longitude: -77.036871,
    tags: ["kayaking", "swimming"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Mountain Trek",
    cost: 100,
    description:
      "Experience the beauty of the mountains on this challenging trek through rough terrain and breathtaking views.",
    location: "Rocky Mountains",
    latitude: 40.3428,
    longitude: -105.6836,
    tags: ["hiking", "camping", "mountain"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Fishing Expedition",
    cost: 75,
    description:
      "Catch the big one on this guided fishing trip in the heart of the wilderness.",
    location: "Yellowstone National Park",
    latitude: 44.428,
    longitude: -110.5885,
    tags: ["fishing", "camping", "outdoors"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Rock Climbing Adventure",
    cost: 150,
    description:
      "Put your skills to the test on this guided rock climbing excursion through towering cliffs and challenging routes.",
    location: "Yosemite National Park",
    latitude: 37.8651,
    longitude: -119.5383,
    tags: ["rock climbing", "outdoors", "adventure"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Canoeing in the Wilderness",
    cost: 50,
    description:
      "Explore serene lakes and winding rivers on this guided canoeing trip through the heart of the wilderness.",
    location: "Boundary Waters Canoe Area Wilderness",
    latitude: 48.668,
    longitude: -92.9951,
    tags: ["canoeing", "camping", "wilderness"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Sailing the Open Seas",
    cost: 200,
    description:
      "Set sail on the open seas and experience the thrill of the wind in your hair on this guided sailing adventure.",
    location: "Bahamas",
    latitude: 25.0478,
    longitude: -77.3554,
    tags: ["sailing", "adventure", "ocean"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Kayaking in the Wilderness",
    cost: 75,
    description:
      "Explore hidden coves and tranquil waters on this guided kayaking trip through the wilderness.",
    location: "Olympic National Park",
    latitude: 47.8083,
    longitude: -123.9549,
    tags: ["kayaking", "wilderness", "outdoors"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Skiing in the Mountains",
    cost: 150,
    description:
      "Experience the rush of skiing down the mountain on this guided skiing excursion through the beautiful Rocky Mountains.",
    location: "Rocky Mountains",
    latitude: 40.3428,
    longitude: -105.6836,
    tags: ["skiing", "mountains", "outdoors"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Snowboarding in the Backcountry",
    cost: 200,
    description:
      "Take on the backcountry on this guided snowboarding excursion through untouched powder and rugged terrain.",
    location: "Sierra Nevada Mountains",
    latitude: 38.5666,
    longitude: -119.9201,
    tags: ["snowboarding", "backcountry", "mountains"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Horseback Riding Lessons",
    cost: 100,
    description:
      "Learn the basics of horseback riding on this guided lesson through beautiful trails and scenic landscapes.",
    location: "Grand Canyon",
    latitude: 36.1069,
    longitude: -112.1126,
    tags: ["riding", "lessons", "outdoors"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Swimming in the Ocean",
    cost: 50,
    description:
      "Dive into the crystal clear waters of the ocean on this guided swimming excursion through beautiful beaches and coral reefs.",
    location: "Hawaii",
    latitude: 19.8968,
    longitude: -155.5828,
    tags: ["swimming", "ocean", "beach"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Rock Climbing Adventure",
    cost: 150,
    description:
      "Challenge yourself on this guided rock climbing excursion through rugged terrain and breathtaking views.",
    location: "Yosemite National Park",
    latitude: 37.8651,
    longitude: -119.5383,
    tags: ["rock climbing", "adventure", "outdoors"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Fishing in the River",
    cost: 75,
    description:
      "Cast your line and reel in the big one on this guided fishing excursion through beautiful rivers and streams.",
    location: "Yellowstone National Park",
    latitude: 44.428,
    longitude: -110.5885,
    tags: ["fishing", "rivers", "outdoors"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Canoeing on the Lake",
    cost: 100,
    description:
      "Explore the beauty of nature on this guided canoeing excursion through serene lakes and picturesque landscapes.",
    location: "Adirondack Mountains",
    latitude: 44.1221,
    longitude: -74.0289,
    tags: ["canoeing", "lakes", "outdoors"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Camping in the Wilderness",
    cost: 75,
    description:
      "Experience the great outdoors on this guided camping excursion through the wilderness and beautiful landscapes.",
    location: "Great Smoky Mountains",
    latitude: 35.6406,
    longitude: -83.6875,
    tags: ["camping", "wilderness", "outdoors"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Kayaking on the River",
    cost: 120,
    description:
      "Paddle through the rapids on this guided kayaking excursion through beautiful rivers and scenic landscapes.",
    location: "Grand Canyon",
    latitude: 36.1069,
    longitude: -112.1126,
    tags: ["kayaking", "rivers", "outdoors"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Sailing on the Sea",
    cost: 200,
    description:
      "Set sail on this guided sailing excursion through beautiful seas and picturesque landscapes.",
    location: "San Francisco Bay",
    latitude: 37.7749,
    longitude: -122.4194,
    tags: ["sailing", "sea", "outdoors"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Skiing in the Mountains",
    cost: 150,
    description:
      "Hit the slopes on this guided skiing excursion through beautiful mountains and picturesque landscapes.",
    location: "Aspen, Colorado",
    latitude: 39.1911,
    longitude: -106.8175,
    tags: ["skiing", "mountains", "outdoors"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Hiking in the Rainforest",
    cost: 100,
    description:
      "Explore the lush greenery and diverse wildlife on this guided hiking excursion through the rainforest.",
    location: "Amazon Rainforest",
    latitude: -3.129,
    longitude: -60.0217,
    tags: ["hiking", "rainforest", "outdoors"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Riding on the Beach",
    cost: 150,
    description:
      "Enjoy the ocean breeze and beautiful views on this guided horseback riding excursion on the beach.",
    location: "Malibu Beach",
    latitude: 34.0259,
    longitude: -118.7798,
    tags: ["riding", "beach", "outdoors"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Swimming in the Oceans",
    cost: 100,
    description:
      "Explore the deep blue sea and discover the marine life on this guided swimming excursion in the ocean.",
    location: "Great Barrier Reef",
    latitude: -18.2828,
    longitude: 147.8222,
    tags: ["swimming", "ocean", "outdoors"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Rock Climbing Adventure in Joshua Tree",
    cost: 150,
    description:
      "Experience the thrill of rock climbing in the beautiful Joshua Tree National Park with a certified guide. All equipment provided.",
    location: "Joshua Tree, California",
    latitude: 34.1388,
    longitude: -116.307,
    tags: ["rock climbing", "lessons"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Sailing in the San Juan Islands",
    cost: 350,
    description:
      "Explore the picturesque San Juan Islands by sailboat with an experienced captain. Includes lunch and snacks.",
    location: "San Juan Islands, Washington",
    latitude: 48.5652,
    longitude: -123.2428,
    tags: ["sailing"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Fishing on the Kenai River",
    cost: 250,
    description:
      "Catch wild salmon on the Kenai River with a experienced guide. All equipment and fishing license provided.",
    location: "Kenai River, Alaska",
    latitude: 60.5544,
    longitude: -151.2591,
    tags: ["fishing"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Camping in Yosemite National Park",
    cost: 50,
    description:
      "Spend a night in the great outdoors at one of Yosemite's campgrounds. Bring your own gear or rent from the park.",
    location: "Yosemite National Park, California",
    latitude: 37.8651,
    longitude: -119.5383,
    tags: ["camping"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Kayaking on the Colorado River",
    cost: 125,
    description:
      "Paddle through the scenic canyons of the Colorado River with a certified guide. All equipment provided.",
    location: "Grand Canyon, Arizona",
    latitude: 36.1069,
    longitude: -112.1126,
    tags: ["kayaking"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Skiing in Vail",
    cost: 150,
    description:
      "Hit the slopes at one of the top ski resorts in the country. Lift ticket and equipment rental included.",
    location: "Vail, Colorado",
    latitude: 39.6403,
    longitude: -106.3742,
    tags: ["skiing"],
    wyn: [],
    wyg: [],
  },
  {
    name: "Hiking in the Adirondacks",
    cost: 0,
    description:
      "Explore the stunning wilderness of the Adirondack Mountains on a guided hike. No experience necessary.",
    location: "Adirondack Mountains, New York",
    latitude: 44.0667,
    longitude: -74.1667,
    tags: ["hiking"],
    wyn: [],
    wyg: [],
  },
];
